Module2
antonpus/nodejs-mentoring pull request #3
Opened 2019-02-17 12:29 UTC by antonpus

2019-02-18 12:50 UTC, vinfinit requested changes
Need to be fixed: 1.
Please, fix the bug with files removing.

2019-02-18 12:50 UTC, vinfinit commented on src/app.js
> +const getDirPath = () => `${path.dirname(require.main.filename)}/../data`;
Clearer way 
```javascript
const getDirPath = () => `${__dirname}/../data`;
```

2019-02-18 12:50 UTC, vinfinit commented on src/dirwatcher.js
> +    this.watchedFiles.push(fileName);
Need to be fixed:
Don't react when a user removes files. As a result, when you remove a file and then add a file with the same file name there is no reaction.
Expected: when a user removes files, the files should be excluded from watchedFiles array.

2019-02-18 12:50 UTC, vinfinit commented on src/dirwatcher.js
> +const watchNewFiles = function watchNewFiles(dirPath, fileNames) {
Private functions are cool.

2019-02-18 13:48 UTC, antonpus commented on src/dirwatcher.js
> +    this.watchedFiles.push(fileName);
Done.

2019-02-18 13:48 UTC, antonpus commented on src/app.js
> +const getDirPath = () => `${path.dirname(require.main.filename)}/../data`;
thnx, fixed.

2019-02-20 10:18 UTC, vinfinit approved these changes

2019-02-20 10:18 UTC, merged